version: '3'
name: teedy-app

services:
# Teedy Application
  teedy-server:
    container_name: teedy-server
    image: sismics/docs:latest
    restart: unless-stopped
    ports:
      # Map internal port to host
      - 8080:8080
    environment:
      # Base url to be used
      DOCS_BASE_URL: "http://localhost"
      # Set the admin email
      DOCS_ADMIN_EMAIL_INIT: "admin@admin.com"
      # Set the admin password (in this example: "superSecure")
      DOCS_ADMIN_PASSWORD_INIT: "$$2a$$05$$PcMNUbJvsk7QHFSfEIDaIOjk1VI9/E7IPjTKx.jkjPxkx2EOKSoPS"
      # Setup the database connection. "teedy-db" is the hostname
      # and "teedy" is the name of the database the application
      # will connect to.
      DATABASE_URL: "jdbc:postgresql://teedy-db:5432/teedy"
      DATABASE_USER: "teedy_db_user"
      DATABASE_PASSWORD: "teedy_db_password"
      DATABASE_POOL_SIZE: "10"
    volumes:
      - ${PWD}/docs/data:/data
      - ${PWD}/docs.xml:/app/webapps/docs.xml
      - ${PWD}/docs-web/target/docs-web-1.12-SNAPSHOT.war:/app/webapps/docs.war
    networks:
      - app-tier
    depends_on:
      - teedy-db

# DB for Teedy
  teedy-db:
    container_name: teedy-db
    image: postgres:13.1-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "teedy_db_user"
      POSTGRES_PASSWORD: "teedy_db_password"
      POSTGRES_DB: "teedy"
    volumes:
      - ${PWD}/docs/db:/var/lib/postgresql/data
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge
    external: true